language: node_js
sudo: true
before_install:
  - sudo apt-get update
  - sudo apt-get install -y -q stunnel4
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
node_js:
  - "0.10"
  - "0.12"
  - "4.0"
  - "iojs"
after_success: npm run coveralls
